# Generated by Django 3.1.7 on 2021-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Primer apellido'),
        ),
    ]
