# Generated by Django 3.1.7 on 2021-03-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210321_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo nombre'),
        ),
    ]
